site_name: 0d4y
site_description: Exploring Cryptography and its impact on quantum information science, cryptography, and secure communication
site_url: https://0d4y.ir

theme:
  name: terminal
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
plugins:
  - search
  # - blog

nav:  
  - ~/intro/:
  - ~/crypto/:
  - ~/protocols/:
  - ~/documents/papers: