site_name: Quantum Key Distribution
site_description: Exploring Quantum Key Distribution (QKD) and its impact on quantum information science, cryptography, and secure communication
site_url: https://q-kd.ir

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
plugins:
  - search
  - blog

nav:  
  - Introduction:
      - Quantum Cryptography: intro/qkd.md
  - Quantum Concepts:
      - Quantum Mechanics: quantum/mechanics.md
      - Entanglement: quantum/entanglement.md
  - Implementation:
      - BB84 Protocol: impl/bb84.md
      - B92 Protocol: impl/b92.md
      - E91 Protocol: impl/e91.md
  - Papers:
      - Micius quantum experiments in space: https://arxiv.org/abs/2208.10236
      - Satellite-to-ground quantum key distribution: https://arxiv.org/pdf/1707.00542