site_name: Quantum Key Distribution
site_description: Exploring Quantum Key Distribution (QKD) and its impact on quantum information science, cryptography, and secure communication
site_url: https://q-kd.ir

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
plugins:
  - search
  - blog

nav:
  - Home: index.md
  - Introduction:
      - What is QKD?: intro/qkd.md
      - History of QKD: intro/history.md
  - Quantum Concepts:
      - Quantum Mechanics: quantum/mechanics.md
      - Entanglement: quantum/entanglement.md
  - Implementation:
      - BB84 Protocol: impl/bb84.md
      - E91 Protocol: impl/e91.md
  - Challenges & Future: future.md
  - About: about.md