site_name: 0d4y
site_description: Exploring Cryptography and its impact on quantum information science, cryptography, and secure communication
site_url: https://0d4y.ir

theme:
  name: terminal
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
plugins:
  - search
  # - blog

nav:  
  - ~/intro/:
      - Quantum Cryptography: intro/qkd.md
  - ~/crypto/:
      - Classical Cryptography: quantum/mechanics.md
  - ~/protocols/:
      - BB84 Protocol: impl/bb84.md
      - B92 Protocol: impl/b92.md
      - E91 Protocol: impl/e91.md
  - ~/writeups/:
      - w1: impl/bb84.md
      - w2: impl/b92.md
      - w3: impl/e91.md
  - ~/documents/papers:
      - Micius quantum experiments in space: https://arxiv.org/abs/2208.10236
      - Satellite-to-ground quantum key distribution: https://arxiv.org/pdf/1707.00542