name: Deploy MkDocs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Build MkDocs site
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force

      - name: Restore CNAME
        run: |
          echo "0d4y.ir" > site/CNAME
          mkdocs gh-deploy --force